packages:
  - "apps/*"
  - "packages/*"
  - "packages/features/*"

catalog:
  tailwindcss: 4.3.3
  "@tailwindcss/cli": 4.3.3
  "@tailwindcss/postcss": 4.3.3
  postcss: 8.5.26

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
